/**
 * Board shape, validation, and blanks.
 *
 * One schema serves all three ways a board can come into existence — typed by
 * the host, generated by Claude, or pasted in as JSON — so a hand-written board
 * and a generated one are indistinguishable downstream.
 */

import { z } from "zod";

export const CLUE_VALUES = [100, 200, 300, 400, 500];
export const NUM_CATEGORIES = 6;

const ClueSchema = z.object({
  value: z.number().int().positive(),
  clue: z.string().max(400),
  answer: z.string().max(200),
  revealed: z.boolean().default(false),
  /** Set only for a Daily Double; overrides `value` when scoring. */
  wager: z.number().int().nullable().default(null),
});

const CategorySchema = z.object({
  title: z.string().max(40),
  clues: z.array(ClueSchema).length(CLUE_VALUES.length),
});

export const BoardSchema = z.object({
  categories: z.array(CategorySchema).min(1).max(NUM_CATEGORIES),
});

export function blankCategory(title = "") {
  return {
    title,
    clues: CLUE_VALUES.map((value) => ({
      value,
      clue: "",
      answer: "",
      revealed: false,
      wager: null,
    })),
  };
}

export function blankBoard() {
  return {
    categories: Array.from({ length: NUM_CATEGORIES }, () => blankCategory()),
  };
}

/**
 * Validates an untrusted board (host-typed or pasted JSON).
 *
 * @returns {{ok: true, board: object} | {ok: false, error: string}}
 */
export function validateBoard(input) {
  const parsed = BoardSchema.safeParse(input);
  if (!parsed.success) {
    const first = parsed.error.issues[0];
    return { ok: false, error: `${first.path.join(".") || "board"}: ${first.message}` };
  }

  const board = parsed.data;

  // A board is only playable if every category is actually filled in. Empty
  // categories are fine while authoring but must not reach the game.
  const empties = [];
  board.categories.forEach((cat, i) => {
    if (!cat.title.trim()) {
      empties.push(`category ${i + 1} has no title`);
      return;
    }
    cat.clues.forEach((clue, q) => {
      if (!clue.clue.trim() || !clue.answer.trim()) {
        empties.push(`"${cat.title}" $${clue.value} is incomplete`);
      }
    });
  });
  if (empties.length) {
    return { ok: false, error: empties.slice(0, 4).join("; ") };
  }

  return { ok: true, board };
}

/** Drops unfilled categories, so a host can play a 3-category board. */
export function compactBoard(board) {
  const categories = board.categories.filter(
    (cat) =>
      cat.title.trim() &&
      cat.clues.some((c) => c.clue.trim() || c.answer.trim()),
  );
  return { categories };
}

/** Every answer currently on the board — fed back to Claude to avoid repeats. */
export function collectAnswers(board) {
  if (!board) return [];
  return board.categories
    .flatMap((cat) => cat.clues.map((c) => c.answer))
    .map((a) => a.trim())
    .filter(Boolean);
}
