/**
 * Board shape, validation, and blanks.
 *
 * One schema serves all three ways a board can come into existence — typed by
 * the host, generated by Claude, or pasted in as JSON — so a hand-written board
 * and a generated one are indistinguishable downstream.
 */

import { z } from "zod";

export const ROUND_VALUES = [
  [100, 200, 300, 400, 500],
  [200, 400, 600, 800, 1000],
];
/** Round 1's values. Kept under the old name because generation imports it. */
export const CLUE_VALUES = ROUND_VALUES[0];
/** The most categories a round may hold. A round may have as few as one. */
export const MAX_CATEGORIES = 6;
export const NUM_ROUNDS = ROUND_VALUES.length;

const ClueSchema = z.object({
  value: z.number().int().positive(),
  clue: z.string().max(400),
  answer: z.string().max(200),
  revealed: z.boolean().default(false),
  /** The bet a player locked in on a Daily Double; overrides `value` when scoring. */
  wager: z.number().int().nullable().default(null),
  /**
   * Whether this square is the Daily Double. Assigned at `startGame`, not while
   * authoring — the default keeps boards saved before this existed loading fine.
   */
  dailyDouble: z.boolean().default(false),
});

const CategorySchema = z.object({
  title: z.string().max(40),
  clues: z.array(ClueSchema).length(ROUND_VALUES[0].length),
});

// No `.min(1)`: a round the host never filled in compacts to zero categories,
// and that must stay parseable so an untouched round 2 cannot block the game.
const RoundSchema = z.object({
  categories: z.array(CategorySchema).max(MAX_CATEGORIES),
});

const FinalSchema = z
  .object({
    category: z.string().max(40),
    clue: z.string().max(400),
    answer: z.string().max(200),
  })
  .nullable()
  .default(null);

export const BoardSchema = z.object({
  rounds: z.array(RoundSchema).min(1).max(NUM_ROUNDS),
  final: FinalSchema,
  options: z
    .object({
      doubleRound: z.boolean().default(false),
      finalRound: z.boolean().default(false),
    })
    .default({ doubleRound: false, finalRound: false }),
});

export function blankCategory(title = "", round = 0) {
  return {
    title,
    clues: ROUND_VALUES[round].map((value) => ({
      value,
      clue: "",
      answer: "",
      revealed: false,
      wager: null,
      dailyDouble: false,
    })),
  };
}

export function blankRound(round) {
  return {
    categories: Array.from({ length: MAX_CATEGORIES }, () => blankCategory("", round)),
  };
}

export function blankBoard() {
  return {
    rounds: Array.from({ length: NUM_ROUNDS }, (_, r) => blankRound(r)),
    final: null,
    options: { doubleRound: false, finalRound: false },
  };
}

/**
 * Validates an untrusted board (host-typed or pasted JSON).
 *
 * @returns {{ok: true, board: object} | {ok: false, error: string}}
 */
export function validateBoard(input) {
  if (!input || !Array.isArray(input.rounds)) {
    return { ok: false, error: "board: expected a rounds array" };
  }

  const parsed = BoardSchema.safeParse(input);
  if (!parsed.success) {
    const first = parsed.error.issues[0];
    return { ok: false, error: `${first.path.join(".") || "board"}: ${first.message}` };
  }

  const board = parsed.data;

  // Only a round that will actually be played has to be complete. An untouched
  // round 2 sitting behind an off toggle must never block the game.
  const empties = [];
  playedRounds(board).forEach((round, r) => {
    if (round.categories.length === 0) {
      empties.push(`round ${r + 1} has no categories`);
      return;
    }
    round.categories.forEach((cat, i) => {
      if (!cat.title.trim()) {
        empties.push(`round ${r + 1} category ${i + 1} has no title`);
        return;
      }
      cat.clues.forEach((clue, q) => {
        if (!clue.clue.trim() || !clue.answer.trim()) {
          empties.push(`"${cat.title}" $${clue.value} is incomplete`);
        }
        // The host page keeps its own copy of ROUND_VALUES, so this is the one
        // place that can catch the two drifting apart — or a hand-posted board
        // playing round 2 at round 1's values, which would halve every wager
        // ceiling without anything else noticing.
        if (clue.value !== ROUND_VALUES[r][q]) {
          empties.push(
            `"${cat.title}" clue ${q + 1} should be worth $${ROUND_VALUES[r][q]}, not $${clue.value}`,
          );
        }
      });
    });
  });
  if (empties.length) {
    return { ok: false, error: empties.slice(0, 4).join("; ") };
  }

  return { ok: true, board };
}

/** The rounds that will actually be played, given the toggles. */
export function playedRounds(board) {
  return board.options?.doubleRound
    ? board.rounds.slice(0, NUM_ROUNDS)
    : board.rounds.slice(0, 1);
}

/**
 * Drops unfilled categories from every round, so a host can play a 3-category
 * board. Both rounds are kept whatever the toggles say, so turning round 2 off
 * and on again does not lose the work.
 */
export function compactBoard(board) {
  // Total by construction: this runs on half-written drafts straight off a
  // socket, and a throw in here takes the whole process down with it.
  const text = (v) => (typeof v === "string" ? v : "");
  const filled = (cat) =>
    cat &&
    text(cat.title).trim() &&
    Array.isArray(cat.clues) &&
    cat.clues.some((c) => c && (text(c.clue).trim() || text(c.answer).trim()));

  return {
    rounds: (board?.rounds ?? []).map((round) => ({
      categories: (round?.categories ?? []).filter(filled),
    })),
    final: board.final ?? null,
    options: {
      doubleRound: Boolean(board.options?.doubleRound),
      finalRound: Boolean(board.options?.finalRound),
    },
  };
}

/** Every answer anywhere on the board — fed back to the model to avoid repeats. */
export function collectAnswers(board) {
  if (!board?.rounds) return [];
  const fromRounds = board.rounds.flatMap((round) =>
    round.categories.flatMap((cat) => cat.clues.map((c) => c.answer)),
  );
  return [...fromRounds, board.final?.answer ?? ""].map((a) => String(a).trim()).filter(Boolean);
}
